### ISSUE TITLE
TODO:  compare the performance of clang pythong binding and clang -cc1 use the fastest one

### ISSUE THREAD

**Issue by roxma** [roxma/clang_complete#1]

**Comment by jsfaint** [comment]
I just saw this issue, maybe useful for you😁
https://github.com/tweekmonster/deoplete-clang2/issues/2

**Comment by roxma** [comment]
@jsfaint Thanks for the information

I'm out of time recently and this issue is kind of low priority (because it is not a bug). There is no ETA currently.

**Comment by jsfaint** [comment]
@roxma It's OK 😄 I'm not pushing you on this

**Comment by roxma** [comment]
https://github.com/roxma/ncm-clang deprecates this project. I'll stick with the `clang -cc1` implementation

I haven't done the comparison, though, and non of them is much faster than the other.

There're some library dependency issues when using the python binding with a python distribution compiled against old version libstdc++, which makes me give up the python implementation.

**Comment by roxma** [comment]
After some more test,

I noticed that the completion gets really fast after caching the TU and an  extra explicit reparse.

I don't know why it needs an explicit reparse.

current experimental repo: https://github.com/ncm2/ncm2-libclang

I'm going to test the python binding again, the official libclang python binding now  supports python3.

**Comment by roxma** [comment]
https://github.com/ncm2/ncm2-pyclang deprecates this repo
