### ISSUE TITLE
Not works on vim8 with python3

### ISSUE THREAD

**Issue by jsfaint** [roxma/clang_complete#2]
The plugin report the following error message since this commit c49d4d1f18fdbd0ed45578796a0b14c8f784d8a9
![image](https://cloud.githubusercontent.com/assets/571829/24441499/670c6c82-148c-11e7-9100-440faa6869df.png)

**Comment by roxma** [comment]
Sorry for the update without testing on python3.

Pull the updates, it should be working now.

**Comment by jsfaint** [comment]
works now, thanks 👍
